USE master
GO

IF EXISTS(SELECT 1 FROM sys.databases WHERE name = 'DB_QLBANSACH')
BEGIN
    DROP DATABASE DB_QLBANSACH
END

CREATE DATABASE DB_QLBANSACH
GO

USE DB_QLBANSACH
GO

CREATE TABLE KHACH_HANG(
    MaKH INT PRIMARY KEY IDENTITY(1,1),
    TaiKhoan VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(50),
    Email VARCHAR(50) NOT NULL UNIQUE,
    DiaChi NVARCHAR(100),
    DienThoai VARCHAR(50) NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    NgaySinh DATE,
    HoTen NVARCHAR(50) NOT NULL
)

CREATE TABLE DON_HANG(
    MaDonHang INT PRIMARY KEY IDENTITY(1,1),
    MaKH INT NOT NULL,
    NgayGiao DATETIME NOT NULL,
    NgayDat DATETIME NOT NULL,
    TinhTrangGH NVARCHAR(50) NOT NULL,
    DaThanhToan bit NOT NULL DEFAULT 0
)
ALTER TABLE DON_HANG ADD CONSTRAINT FK_DON_HANG_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH) -- ON DELETE CASCADE

CREATE TABLE TAC_GIA(
    MaTacGia INT PRIMARY KEY IDENTITY(1,1),
    TenTacGia NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100),
    TieuSu NTEXT,
    DienThoai VARCHAR(50) NOT NULL
)

CREATE TABLE CHU_DE(
    MaChuDe INT PRIMARY KEY IDENTITY(1,1),
    TenChuDe NVARCHAR(50) NOT NULL UNIQUE,
)

CREATE TABLE NHA_XUAT_BAN(
    MaNXB INT PRIMARY KEY IDENTITY(1,1),
    TenNXB NVARCHAR(50) NOT NULL,
    DienThoai VARCHAR(50) NOT NULL UNIQUE,
    DiaChi NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE SACH(
    MaSach INT PRIMARY KEY IDENTITY(1,1),
    TenSach NVARCHAR(50) NOT NULL,
    GiaBan NUMERIC(18,2),
    MoTa NTEXT,
    AnhBia VARCHAR(MAX), /*url hinh anh*/
    NgayCapNhat DATETIME DEFAULT SYSDATETIME(),
    SoLuongTon INT DEFAULT 0
)

/* SACH & TAC_GIA */

CREATE TABLE SACH_TACGIA(
    MaSach INT,
    MaTacGia INT,
    VaiTro NVARCHAR(50),
    ViTri NVARCHAR(50),

    PRIMARY KEY(MaSach, MaTacGia)
)
ALTER TABLE SACH_TACGIA ADD CONSTRAINT FK_SACH_TACGIA_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach) -- ON DELETE CASCADE
ALTER TABLE SACH_TACGIA ADD CONSTRAINT FK_SACH_TACGIA_TAC_GIA FOREIGN KEY (MaTacGia) REFERENCES TAC_GIA(MaTacGia) -- ON DELETE CASCADE

/* SACH & CHU_DE */

CREATE TABLE SACH_CHUDE(
    MaSach INT,
    MaChuDe INT

    PRIMARY KEY(MaSach, MaChuDe)
)
ALTER TABLE SACH_CHUDE ADD CONSTRAINT FK_SACH_CHUDE_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach) -- ON DELETE CASCADE
ALTER TABLE SACH_CHUDE ADD CONSTRAINT FK_SACH_CHUDE_CHU_DE FOREIGN KEY (MaChuDe) REFERENCES CHU_DE(MaChuDe) -- ON DELETE CASCADE

/* SACH & NHA_XUAT_BAN */

CREATE TABLE SACH_NHAXUATBAN(
    MaSach INT,
    MaNXB INT

    PRIMARY KEY(MaSach, MaNXB)
)
ALTER TABLE SACH_NHAXUATBAN ADD CONSTRAINT FK_SACH_NHAXUATBAN_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach) -- ON DELETE CASCADE
ALTER TABLE SACH_NHAXUATBAN ADD CONSTRAINT FK_SACH_NHAXUATBAN_NHA_XUAT_BAN FOREIGN KEY (MaNXB) REFERENCES NHA_XUAT_BAN(MaNXB) -- ON DELETE CASCADE

/* DON_HANG & SACH -> CHI_TIET_DON_HANG */

CREATE TABLE CHI_TIET_DON_HANG(
    MaDonHang INT,
    MaSach INT,
    SoLuong INT NOT NULL,
    DonGia INT

    PRIMARY KEY(MaDonHang, MaSach)
)
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CHI_TIET_DON_HANG_DON_HANG FOREIGN KEY (MaDonHang) REFERENCES DON_HANG(MaDonHang) -- ON DELETE CASCADE
ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CHI_TIET_DON_HANG_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach) -- ON DELETE CASCADE

/* Thêm dữ liệu */
/* TAC_GIA */
INSERT INTO TAC_GIA VALUES(N'Nguyễn Giả 1', NULL, NULL, '088215690')
INSERT INTO TAC_GIA VALUES(N'Nguyễn Giả 2', NULL, NULL, '088215691')
INSERT INTO TAC_GIA VALUES(N'Nguyễn Giả 3', NULL, NULL, '088215692')
INSERT INTO TAC_GIA VALUES(N'Nguyễn Giả 4', NULL, NULL, '088215693')
/* CHU_DE */
INSERT INTO CHU_DE VALUES(N'Phiêu lưu')
INSERT INTO CHU_DE VALUES(N'Viễn tưởng')
/* NHA_XUAT_BAN */
INSERT INTO NHA_XUAT_BAN VALUES(N'Kim Đồng 1', '888111333', N'123 Đường A, Quận P, TP.X')
INSERT INTO NHA_XUAT_BAN VALUES(N'Kim Đồng 2', '888111222', N'456 Đường A, Quận P, TP.X')
/* SACH */
INSERT INTO SACH VALUES(N'SAO 1', 10000, N'Câu chuyện nói về ...', '/img/bia/sao1.jpg', null, 20)
INSERT INTO SACH VALUES(N'SAO 2', 5000, N'Câu chuyện nói về ...', '/img/bia/sao2.jpg', null, 50)
/* SACH_TACGIA */
INSERT INTO SACH_TACGIA VALUES(1, 1, N'Viết kịch bản', N'Tác giả')
INSERT INTO SACH_TACGIA VALUES(1, 3, N'Vẽ minh họa', N'Minh họa cho sách')
INSERT INTO SACH_TACGIA VALUES(2, 2, N'Hoàn thiện kịch bản', N'Tác giả')
INSERT INTO SACH_TACGIA VALUES(2, 4, N'Viết kịch bản', N'Tác giả')
/* SACH_CHUDE */
INSERT INTO SACH_CHUDE VALUES(1, 2)
INSERT INTO SACH_CHUDE VALUES(2, 1)
/* SACH_NHAXUATBAN */
INSERT INTO SACH_NHAXUATBAN VALUES(1, 1)
INSERT INTO SACH_NHAXUATBAN VALUES(1, 2)
INSERT INTO SACH_NHAXUATBAN VALUES(2, 2)
/* KHACH_HANG */
INSERT INTO KHACH_HANG(HoTen, TaiKhoan, MatKhau, Email, DiaChi, DienThoai, GioiTinh, NgaySinh) VALUES(N'Nguyễn Văn A', 'VanA123', '123456', 'NguyenA@gmail.com', NULL, '0123456789', N'Nam', CONVERT(DATE, '01/01/2000', 103))
INSERT INTO KHACH_HANG(HoTen, TaiKhoan, MatKhau, Email, DiaChi, DienThoai, GioiTinh, NgaySinh) VALUES(N'Nguyễn Văn B', 'VanB123', '654321', 'NguyenB@gmail.com', NULL, '0987654321', N'Nữ', CONVERT(DATE, '12/12/2000', 103))
/* DON_HANG */
INSERT INTO DON_HANG VALUES(2, CONVERT(DATE, '01/02/2025', 103), CONVERT(DATE, '01/01/2025', 103), N'Đã giao', 1)
INSERT INTO DON_HANG VALUES(1, CONVERT(DATE, '03/02/2025', 103), CONVERT(DATE, '04/03/2025', 103), N'Chưa giao', 0)
/* CHI_TIET_DON_HANG*/
INSERT INTO CHI_TIET_DON_HANG VALUES(1, 2, 5, 5000)
INSERT INTO CHI_TIET_DON_HANG VALUES(2, 1, 10, 10000)
INSERT INTO CHI_TIET_DON_HANG VALUES(2, 2, 7, 5000)

SELECT * FROM TAC_GIA
SELECT * FROM CHU_DE
SELECT * FROM NHA_XUAT_BAN
SELECT * FROM SACH
SELECT * FROM SACH_TACGIA
SELECT * FROM SACH_CHUDE
SELECT * FROM SACH_NHAXUATBAN
SELECT * FROM KHACH_HANG
SELECT * FROM DON_HANG
SELECT * FROM CHI_TIET_DON_HANG